version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: devrunner
    container_name: dappi-beta
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src:/app/src                      # Live TS code
      - ./tsconfig.json:/app/tsconfig.json  # TS config
      - ./package.json:/app/package.json    # Scripts and deps
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
    command: ["npm", "run", "dev"]
